apiVersion: v1
kind: Secret
metadata:
  name: mongodb_secret
type: Opaque
data:
  MONGO_ROOT_USERNAME: admin
  MONGO_ROOT_PASSWORD: password
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        envFrom:
        - secretRef:
            name: mongodb_secret
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  clusterIP: None
  selector:
    app: mongodb
